bot:
  token: 8165969282:AAHQlAcwiD660YOgrTGP4gHsZUSGfwBaNNo
  username: "@MarketDBNotifiaction_Test_Bot"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/herald
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/main.xml